android.useAndroidX=true
android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
org.gradle.jvmargs=-Xmx2048m
android.suppressUnsupportedCompileSdk=36
android.injected.test.ignoreUnsupportedCompileSdk=true
android.buildManager.checkAarMetadata=false
android.overridePathCheck=true
android.injected.test.ignoreUnsupportedCompileSdk=true