name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Unzip project
      run: |
        unzip -q sout_we_rouh.zip -d extracted_project
        shopt -s dotglob
        mv extracted_project/*/* extracted_project/ 2>/dev/null || true
        mv extracted_project/* ./ 2>/dev/null || true

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.47.1'
        channel: 'stable'

    - name: Get Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
